name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./apps/http-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir  -p /home/runner/.ssh
          ls /home/runner/.ssh
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.201.10.59 -t "docker stop backend || true;
          docker rm backend || true;
          docker run --name backend -d -p 3001:3001 -e DATABASE_URL=${{ secrets.DATABASE_URL }} WS_URL=${{ secrets.WS_URL }} EMAIL_USER=${{ secrets.EMAIL_USER }} EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} FRONTEND_URL=${{ secrets.FRONTEND_URL }} adarsh9770/backend:${{ github.sha }}"